version: '3.8'

services:
  php:
    container_name: learning_laravel
    image: mustafai96/learning-fpm:1.0
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ../backend:/www
      - ./php/www.conf:/etc/php/8.1/fpm/pool.d/www.conf
    restart: always
    networks:
      - backend-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    networks:
      - backend-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../backend:/www
      - ./nginx/vhost-dev/:/etc/nginx/conf.d/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount nginx.conf
    restart: always
    working_dir: /www
    networks:
      - backend-network
      
  
networks:
  backend-network:
    driver: bridge

